export { LinesInSpaceLab, type LinesInSpaceProps, type LinesMode } from './preset.js';
export {
  add,
  angleBetween,
  clipToSphere,
  cross,
  dot,
  footOfPerpendicular,
  fmt,
  fmtVec,
  lineProblems,
  norm,
  pointAt,
  project,
  relate,
  scale,
  screenCrossing,
  sub,
  unit,
  type Foot,
  type Line3,
  type LinePair,
  type Projected,
  type Relation,
  type V3,
} from './core.js';
