'use client';
import { Button } from '@/components/ui/button';

/**
 * BusinessLesson — the "run a business" story runner (Quantic-style active learning).
 * A creator authors a SCENE SCRIPT (data): one small screen at a time — a line of
 * narration, a decision, a predict-question, or a report — and each decision applies
 * balanced business ACTIONS to a live set of books (the @classytic/stage/finance
 * bizsim engine). The learner runs a business one choice at a time, with a tiny
 * always-visible books panel (cash, profit) that expands to the full income statement
 * and balance sheet — so the accounting emerges from their own decisions and scales
 * to financial analysis at the end.
 *
 * Content-neutral: the SCENARIO (samosa stall, coffee cart, app startup…) is entirely
 * the creator's `scenes` — this file is just the engine + the interactive primitives.
 * DEMO_SCENES below is one authored example, not baked-in content.
 */

import { useMemo, useState, type ReactNode } from 'react';
import {
  initialBiz,
  applyBiz,
  incomeStatement,
  balanceSheet,
  type BizState,
  type BizAction,
} from '@classytic/stage/finance';
import { Readout } from '../../kit/frame.js';
import { AssessedChoiceGroup } from '../../kit/controls.js';
import { AuthoredActivityRuntime } from '../../kit/authored-activity-runtime.js';
import type {
  AuthoredActivity,
  AuthoredChoiceQuestion,
  AuthoredSuccessCondition,
} from '../../kit/activity-authoring.js';
import { EvidencePanel } from '../activity.js';

export type Scene =
  | { kind: 'narrate'; text: string }
  | { kind: 'decide'; prompt: string; choices: { label: string; actions?: BizAction[]; feedback: string }[] }
  | {
      kind: 'predict';
      prompt: string;
      choices: { value: string; label: string }[];
      answer: string;
      explain: string;
    }
  | { kind: 'report'; show: 'income' | 'balance'; note?: string };

export interface BusinessLessonProps {
  scenes?: Scene[];
  init?: Partial<BizState>;
  currency?: string;
  title?: string;
  prompt?: string;
  objectives?: string[];
}

const money =
  (currency: string) =>
  (n: number): string =>
    `${n < 0 ? '−' : ''}${currency}${Math.abs(Math.round(n)).toLocaleString('en-US')}`;

export function BusinessLesson({
  scenes = DEMO_SCENES,
  init = {},
  currency = '$',
  title = 'Run a business',
  prompt = 'Make one decision at a time and watch your books respond.',
  objectives,
}: BusinessLessonProps = {}): ReactNode {
  const fmt = useMemo(() => money(currency), [currency]);
  const [decisions, setDecisions] = useState<Record<number, number>>({});
  const [showBooks, setShowBooks] = useState(false);
  const biz = scenes.reduce((state, item, sceneIndex) => {
    if (item.kind !== 'decide') return state;
    const picked = decisions[sceneIndex];
    if (picked == null) return state;
    return (item.choices[picked]?.actions ?? []).reduce(applyBiz, state);
  }, initialBiz(init));

  const is = incomeStatement(biz),
    bs = balanceSheet(biz);

  const questions: AuthoredChoiceQuestion[] = scenes.flatMap((item, index) =>
    item.kind === 'predict'
      ? [
          {
            id: `scene-${index}-prediction`,
            prompt: item.prompt,
            choices: item.choices,
            answer: item.answer,
            explain: item.explain,
          },
        ]
      : [],
  );
  const success: AuthoredSuccessCondition[] = scenes.reduce<AuthoredSuccessCondition[]>(
    (conditions, item, index) => {
      if (item.kind === 'decide')
        conditions.push({
          id: `scene-${index}-decision`,
          source: 'action',
          key: `decision-${index}`,
          pendingLabel: 'Choose a business action before continuing.',
        });
      if (item.kind === 'predict')
        conditions.push({
          id: `scene-${index}-answer`,
          source: 'answer',
          key: `scene-${index}-prediction`,
          pendingLabel: 'Answer the business prediction before continuing.',
        });
      return conditions;
    },
    [],
  );
  const activity: AuthoredActivity = {
    pattern: 'scenario',
    title,
    objectives: objectives ?? [
      'Connect business decisions to cash and profit',
      'Read reports generated by balanced transactions',
      'Distinguish profit from cash and other assets',
    ],
    questions,
    success,
    steps: scenes.map((item, index) => ({
      id: `scene-${index}`,
      phase:
        item.kind === 'decide'
          ? 'act'
          : item.kind === 'predict'
            ? 'predict'
            : item.kind === 'report'
              ? 'explain'
              : index === scenes.length - 1
                ? 'transfer'
                : 'observe',
      title:
        item.kind === 'decide'
          ? 'Make a business decision'
          : item.kind === 'predict'
            ? 'Predict from the books'
            : item.kind === 'report'
              ? `Read the ${item.show === 'income' ? 'income statement' : 'balance sheet'}`
              : index === 0
                ? 'Enter the scenario'
                : 'Connect the decisions',
      lead:
        item.kind === 'narrate'
          ? item.text
          : item.kind === 'decide'
            ? item.prompt
            : item.kind === 'report'
              ? item.note
              : undefined,
      ...(item.kind === 'decide'
        ? { success: `scene-${index}-decision` }
        : item.kind === 'predict'
          ? { success: `scene-${index}-answer` }
          : {}),
    })),
  };

  const evidence = (
    <EvidencePanel title="Live books">
      <Readout
        value={<>Cash {fmt(biz.cash)}</>}
        sub={
          <>
            profit so far {fmt(is.netProfit)} · stock {fmt(bs.inventory)}
          </>
        }
      />
      <Button
        type="button"
        variant="outline"
        size="sm"
        onClick={() => setShowBooks((v) => !v)}
        className="lab-chip business-books-toggle"
        aria-expanded={showBooks}
      >
        {showBooks ? 'hide the books ▾' : 'the books ▸'}
      </Button>
      {showBooks && (
        <div className="business-books-stack">
          <IncomeTable is={is} fmt={fmt} />
          <BalanceTable bs={bs} fmt={fmt} />
        </div>
      )}
    </EvidencePanel>
  );
  return (
    <AuthoredActivityRuntime
      activity={activity}
      activityId="business-lesson"
      eyebrow="Business simulation"
      title={title}
      description={prompt}
      status={({ sequence }) => (
        <>
          <span>cash {fmt(biz.cash)}</span>
          <span>profit {fmt(is.netProfit)}</span>
          <span>{scenes[sequence.index]?.kind ?? 'complete'}</span>
        </>
      )}
      evidence={evidence}
      observation={({ sequence }) =>
        scenes[sequence.index]?.kind === 'decide' && decisions[sequence.index] != null
          ? 'Your decision has been posted to the live books. Inspect cash, profit, inventory, and the accounting equation before continuing.'
          : 'Every authored action posts a balanced transaction, so the reports emerge from the learner’s own choices.'
      }
      transcript={({ sequence }) =>
        `Scene ${sequence.index + 1} of ${scenes.length}. Cash is ${fmt(biz.cash)}, net profit is ${fmt(is.netProfit)}, inventory is ${fmt(bs.inventory)}, and the balance sheet ${bs.balances ? 'balances' : 'does not balance'}.`
      }
    >
      {({ sequence, complete }) => {
        const scene = scenes[sequence.index];
        const picked = decisions[sequence.index];
        if (!scene) return <p>No scenario scene has been authored.</p>;
        if (scene.kind === 'decide')
          return (
            <div className="business-lesson-scene">
              <AssessedChoiceGroup
                value={picked?.toString()}
                ariaLabel="Choose the business decision"
                onChange={(value) => {
                  const choiceIndex = Number(value);
                  const choice = scene.choices[choiceIndex];
                  if (!choice || picked != null) return;
                  setDecisions((current) => ({ ...current, [sequence.index]: choiceIndex }));
                  complete(`scene-${sequence.index}-decision`, choice.label);
                }}
                options={scene.choices.map((choice, choiceIndex) => ({
                  value: choiceIndex.toString(),
                  label: choice.label,
                  disabled: picked != null,
                }))}
              />
              {picked != null && (
                <p className="business-feedback" role="status">
                  {scene.choices[picked]?.feedback}
                </p>
              )}
            </div>
          );
        if (scene.kind === 'report')
          return (
            <div className="business-lesson-scene">
              {scene.show === 'income' ? (
                <IncomeTable is={is} fmt={fmt} />
              ) : (
                <BalanceTable bs={bs} fmt={fmt} />
              )}
            </div>
          );
        return (
          <div className="business-lesson-scene">
            <Readout
              value={
                scene.kind === 'predict' ? `Cash ${fmt(biz.cash)}` : indexLabel(sequence.index, scenes.length)
              }
              sub={
                scene.kind === 'predict'
                  ? `profit ${fmt(is.netProfit)} · assets ${fmt(bs.totalAssets)}`
                  : `cash ${fmt(biz.cash)} · profit ${fmt(is.netProfit)}`
              }
            />
          </div>
        );
      }}
    </AuthoredActivityRuntime>
  );
}

const indexLabel = (index: number, total: number): string =>
  index === total - 1 ? 'Scenario complete' : `Business scene ${index + 1} of ${total}`;

function IncomeTable({
  is,
  fmt,
}: {
  is: ReturnType<typeof incomeStatement>;
  fmt: (n: number) => string;
}): ReactNode {
  return (
    <div className="business-ledger">
      <div className="business-ledger-title">INCOME STATEMENT</div>
      <div className="business-ledger-row">
        <span>Revenue</span>
        <span>{fmt(is.revenue)}</span>
      </div>
      <div className="business-ledger-row">
        <span>− Cost of sales</span>
        <span>{fmt(is.cogs)}</span>
      </div>
      <div className="business-ledger-row" data-total>
        <span>Gross profit</span>
        <span>{fmt(is.grossProfit)}</span>
      </div>
      <div className="business-ledger-row">
        <span>− Expenses</span>
        <span>{fmt(is.expenses)}</span>
      </div>
      <div className="business-ledger-row" data-total data-tone={is.netProfit >= 0 ? 'good' : 'danger'}>
        <span>Net profit</span>
        <span>{fmt(is.netProfit)}</span>
      </div>
    </div>
  );
}
function BalanceTable({
  bs,
  fmt,
}: {
  bs: ReturnType<typeof balanceSheet>;
  fmt: (n: number) => string;
}): ReactNode {
  return (
    <div className="business-ledger">
      <div className="business-ledger-title">BALANCE SHEET</div>
      <div className="business-ledger-row">
        <span>Cash</span>
        <span>{fmt(bs.cash)}</span>
      </div>
      <div className="business-ledger-row">
        <span>Inventory</span>
        <span>{fmt(bs.inventory)}</span>
      </div>
      <div className="business-ledger-row">
        <span>Equipment</span>
        <span>{fmt(bs.equipment)}</span>
      </div>
      <div className="business-ledger-row" data-total>
        <span>Total assets</span>
        <span>{fmt(bs.totalAssets)}</span>
      </div>
      <div className="business-ledger-row" data-section>
        <span>Loan</span>
        <span>{fmt(bs.loan)}</span>
      </div>
      <div className="business-ledger-row">
        <span>Capital + retained</span>
        <span>{fmt(bs.capital + bs.retained + bs.openProfit)}</span>
      </div>
      <div className="business-ledger-row" data-total>
        <span>Liabilities + equity</span>
        <span>{fmt(bs.totalLiabilitiesEquity)}</span>
      </div>
      <div className="business-ledger-status" data-tone={bs.balances ? 'good' : 'danger'}>
        {bs.balances ? '✓ it balances' : '✗ off'}
      </div>
    </div>
  );
}

/** An authored example scenario, a coffee cart. Creators write their own like this. */
export const DEMO_SCENES: Scene[] = [
  {
    kind: 'narrate',
    text: 'You’re opening a coffee cart. Right now you own nothing but a plan. Let’s build a business.',
  },
  {
    kind: 'decide',
    prompt: 'First you need money to start. Put in some of your own savings as capital?',
    choices: [
      {
        label: 'Invest $500',
        actions: [{ type: 'invest', amount: 500 }],
        feedback:
          'You now have $500 cash, and $500 of owner’s capital. That capital is your stake in the business.',
      },
      {
        label: 'Invest $800',
        actions: [{ type: 'invest', amount: 800 }],
        feedback: 'A bigger stake: $800 cash and $800 of capital to work with.',
      },
    ],
  },
  {
    kind: 'decide',
    prompt: 'A cart costs money. Which do you buy?',
    choices: [
      {
        label: 'A new cart, $300',
        actions: [{ type: 'buyEquipment', amount: 300 }],
        feedback:
          'Cash dropped $300, but you own a $300 cart now. Your wealth didn’t fall, it changed shape from cash into an ASSET.',
      },
      {
        label: 'A used cart, $150',
        actions: [{ type: 'buyEquipment', amount: 150 }],
        feedback: 'Cheaper: $150 cash became a $150 asset. Same idea, cash turned into equipment you own.',
      },
    ],
  },
  {
    kind: 'decide',
    prompt: 'Now buy beans & cups, enough for 100 coffees at $1 each of ingredients.',
    choices: [
      {
        label: 'Buy 100 coffees’ worth ($100)',
        actions: [{ type: 'buyStock', qty: 100, unitCost: 1 }],
        feedback: 'Cash → inventory. Still an asset, just a different kind: $100 of stock ready to sell.',
      },
    ],
  },
  {
    kind: 'decide',
    prompt: 'Time to sell. What do you charge per coffee?',
    choices: [
      {
        label: '$2, cheap, sell all 100',
        actions: [{ type: 'sell', qty: 100, price: 2 }],
        feedback: 'You sold all 100 for $200. Low price, low margin, but nothing left unsold.',
      },
      {
        label: '$3, sell 80',
        actions: [{ type: 'sell', qty: 80, price: 3 }],
        feedback: 'You sold 80 for $240, more revenue than the cheap price, with stock to spare.',
      },
      {
        label: '$5, sell only 40',
        actions: [{ type: 'sell', qty: 40, price: 5 }],
        feedback: 'Only 40 sold, for $200, high price scared buyers off, and lots of beans are left.',
      },
    ],
  },
  {
    kind: 'decide',
    prompt: 'The market charges $50 to rent your pitch for the day.',
    choices: [
      {
        label: 'Pay the $50 rent',
        actions: [{ type: 'expense', amount: 50 }],
        feedback:
          'Rent is an EXPENSE, it lowers profit and cash, but you don’t own anything for it (unlike the cart).',
      },
    ],
  },
  {
    kind: 'predict',
    prompt: 'You made a profit. Is your cash the same amount as your profit?',
    choices: [
      { value: 'no', label: 'No, some cash is tied up in the cart and unsold stock' },
      { value: 'yes', label: 'Yes, profit always equals cash' },
    ],
    answer: 'no',
    explain:
      'Profit and cash are different. You spent cash on the cart and beans (assets), so cash can be lower than profit, that’s why businesses track both.',
  },
  {
    kind: 'report',
    show: 'income',
    note: 'Here’s the day as an income statement, revenue, minus what the coffees cost, minus expenses, equals profit.',
  },
  {
    kind: 'report',
    show: 'balance',
    note: 'And the balance sheet: everything you own (assets) equals what you owe plus your stake (liabilities + equity). It always balances.',
  },
  {
    kind: 'narrate',
    text: 'That’s a whole business: you raised capital, bought assets, priced a product, sold it, and read your own income statement and balance sheet. That’s financial analysis, built from your own decisions.',
  },
];
