/**
 * Generate a schema-free catalog from canonical lab manifests.
 *
 * Metadata remains authored once in manifest.ts. We read its defineLab object with the
 * TypeScript parser and emit only serializable discovery fields, so opening the gallery
 * never imports every Zod schema or manifest module.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import ts from 'typescript';
import { readManifests } from './gen-render-map.mjs';

const CHECK = process.argv.includes('--check');
const root = new URL('../src/domains/', import.meta.url);
const target = new URL('../src/domains/catalog-map.ts', import.meta.url);
const pascal = (id) =>
  id.replace(/-([a-z])/g, (_, c) => c.toUpperCase()).replace(/^./, (c) => c.toUpperCase());

function manifestObject(path, text) {
  const source = ts.createSourceFile(path.pathname, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  let found;
  const visit = (node) => {
    if (
      ts.isCallExpression(node) &&
      node.expression.getText(source) === 'defineLab' &&
      node.arguments[0] &&
      ts.isObjectLiteralExpression(node.arguments[0])
    )
      found = node.arguments[0];
    ts.forEachChild(node, visit);
  };
  visit(source);
  if (!found) throw new Error(`no defineLab({...}) object in ${path.pathname}`);
  const prop = (name) =>
    found.properties.find(
      (p) => ts.isPropertyAssignment(p) && p.name.getText(source).replaceAll(/["']/g, '') === name,
    );
  const value = (name) => {
    const p = prop(name);
    if (!p) throw new Error(`missing ${name} in ${path.pathname}`);
    return p.initializer.getText(source);
  };
  return { value, optional: (name) => prop(name)?.initializer.getText(source) };
}

const rows = readManifests().map((row) => {
  const path = new URL(`${row.domain}/${row.id}/manifest.ts`, root);
  const parsed = manifestObject(path, readFileSync(path, 'utf8'));
  const tag = parsed.optional('tag');
  const tagLine = tag && tag.slice(1, -1) !== pascal(row.id) ? `\n    tag: ${tag},` : '';
  return `  {\n    key: ${parsed.value('id')},${tagLine}\n    label: ${parsed.value('title')},\n    description: ${parsed.value('description')},\n    category: 'interactive',\n    void: true,\n    group: ${parsed.value('group')},\n    domain: ${parsed.value('domain')},\n    taxonomy: ${parsed.value('taxonomy')},\n  },`;
});

const out = `/** GENERATED by scripts/gen-catalog.mjs — schema-free discovery metadata. */\nimport type { LabManifestCatalogEntry } from '../lab-def/to-catalog.js';\n\nexport const generatedManifestCatalog: LabManifestCatalogEntry[] = [\n${rows.join('\n')}\n];\n`;

if (CHECK) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== out) {
    console.error('✗ catalog-map.ts is stale — run: node scripts/gen-catalog.mjs');
    process.exit(1);
  }
  console.log('✓ catalog-map.ts up to date:', rows.length, 'labs');
} else {
  writeFileSync(target, out);
  console.log('wrote src/domains/catalog-map.ts:', rows.length, 'labs');
}
