/** GENERATED by scripts/gen-activity-map.mjs — do not edit.
 * Opt-in quality loaders only; never import from learner catalogs. */
import type { CompiledAuthoredActivity } from '../kit/activity-authoring.js';

export type ActivityPlanLoader = () => Promise<{ activity: CompiledAuthoredActivity }>;

export const activityPlanLoaders: Record<string, ActivityPlanLoader> = {
  'atomic-orbital': () => import('./chem/atomic-orbital/activity.js'),
  'bloch-sphere': () => import('./physics/bloch-sphere/activity.js'),
  'cell-energy': () => import('./biology/cell-energy/activity.js'),
  'cell-system': () => import('./biology/cell-system/activity.js'),
  'crystal-lattice': () => import('./chem/crystal-lattice/activity.js'),
  'double-slit': () => import('./physics/double-slit/activity.js'),
  'fission-chain': () => import('./physics/fission-chain/activity.js'),
  'geometry-foundations': () => import('./math/geometry-foundations/activity.js'),
  'length-contraction': () => import('./physics/length-contraction/activity.js'),
  'lorentz-transformation': () => import('./physics/lorentz-transformation/activity.js'),
  'measurement': () => import('./math/measurement/activity.js'),
  'meiosis-explorer': () => import('./biology/meiosis-explorer/activity.js'),
  'membrane-transport': () => import('./biology/membrane-transport/activity.js'),
  'mitosis-explorer': () => import('./biology/mitosis-explorer/activity.js'),
  'molecular-geometry': () => import('./chem/molecular-geometry/activity.js'),
  'muon-survival': () => import('./physics/muon-survival/activity.js'),
  'nuclear-binding-energy': () => import('./physics/nuclear-binding-energy/activity.js'),
  'orbital-overlap': () => import('./chem/orbital-overlap/activity.js'),
  'photoelectric-effect': () => import('./physics/photoelectric-effect/activity.js'),
  'quantum-gates': () => import('./physics/quantum-gates/activity.js'),
  'relativity-light-clock': () => import('./physics/relativity-light-clock/activity.js'),
  'relativity-simultaneity': () => import('./physics/relativity-simultaneity/activity.js'),
  'spatial-lorentz': () => import('./physics/spatial-lorentz/activity.js'),
  'stereochemistry': () => import('./chem/stereochemistry/activity.js'),
  'uncertainty-wave-packet': () => import('./physics/uncertainty-wave-packet/activity.js'),
  'xray-attenuation': () => import('./physics/xray-attenuation/activity.js'),
  'xray-tube-spectrum': () => import('./physics/xray-tube-spectrum/activity.js'),
};
