/**
 * GENERATED by scripts/gen-manifests.mjs — do not edit by hand. Add a lab folder + run
 * `npm run labs:generate`. Each entry is ONE lab in the canonical model
 * (src/domains/<domain>/<lab-id>/manifest.ts); a manifest pulls only its pure schema + the
 * defineLab factory, never its runtime, so listing every manifest here stays cheap.
 */
import type { LabManifest } from '../lab-def/define-lab.js';

// accounting
import apportion from './accounting/apportion/manifest.js';
import breakEven from './accounting/break-even/manifest.js';
import businessLesson from './accounting/business-lesson/manifest.js';
import compoundInterest from './accounting/compound-interest/manifest.js';
import depreciation from './accounting/depreciation/manifest.js';
import eoq from './accounting/eoq/manifest.js';
import equationBalance from './accounting/equation-balance/manifest.js';
import journalPoster from './accounting/journal-poster/manifest.js';
import limitedCompany from './accounting/limited-company/manifest.js';
import ratioLab from './accounting/ratio-lab/manifest.js';
import reorderPoint from './accounting/reorder-point/manifest.js';
import statementBuilder from './accounting/statement-builder/manifest.js';
import statementSorter from './accounting/statement-sorter/manifest.js';
import warehouseAllocation from './accounting/warehouse-allocation/manifest.js';

// biology
import cellEnergy from './biology/cell-energy/manifest.js';
import cellSystem from './biology/cell-system/manifest.js';
import centralDogma from './biology/central-dogma/manifest.js';
import enzymeRate from './biology/enzyme-rate/manifest.js';
import geneticCross from './biology/genetic-cross/manifest.js';
import meiosisExplorer from './biology/meiosis-explorer/manifest.js';
import membraneTransport from './biology/membrane-transport/manifest.js';
import mitosisExplorer from './biology/mitosis-explorer/manifest.js';
import photosynthesisFactors from './biology/photosynthesis-factors/manifest.js';
import punnettCross from './biology/punnett-cross/manifest.js';
import respiration from './biology/respiration/manifest.js';
import sequence from './biology/sequence/manifest.js';
import sexLinkedCross from './biology/sex-linked-cross/manifest.js';

// chem
import atomicOrbital from './chem/atomic-orbital/manifest.js';
import battery from './chem/battery/manifest.js';
import bohrAtom from './chem/bohr-atom/manifest.js';
import crystalLattice from './chem/crystal-lattice/manifest.js';
import dilution from './chem/dilution/manifest.js';
import electrochem from './chem/electrochem/manifest.js';
import gasBox from './chem/gas-box/manifest.js';
import kinetics from './chem/kinetics/manifest.js';
import leChatelier from './chem/le-chatelier/manifest.js';
import molecularGeometry from './chem/molecular-geometry/manifest.js';
import orbitalOverlap from './chem/orbital-overlap/manifest.js';
import periodicTrends from './chem/periodic-trends/manifest.js';
import reactionLab from './chem/reaction-lab/manifest.js';
import reactionProfile from './chem/reaction-profile/manifest.js';
import solutionBox from './chem/solution-box/manifest.js';
import stereochemistry from './chem/stereochemistry/manifest.js';
import stoichiometry from './chem/stoichiometry/manifest.js';
import titration from './chem/titration/manifest.js';

// circuits
import bjtInside from './circuits/bjt-inside/manifest.js';
import brownout from './circuits/brownout/manifest.js';
import capacitorLeak from './circuits/capacitor-leak/manifest.js';
import circuit from './circuits/circuit/manifest.js';
import circuitBuilder from './circuits/circuit-builder/manifest.js';
import circuitLab from './circuits/circuit-lab/manifest.js';
import circuitScene from './circuits/circuit-scene/manifest.js';
import cmosInverter from './circuits/cmos-inverter/manifest.js';
import cmosNand from './circuits/cmos-nand/manifest.js';
import cmosNor from './circuits/cmos-nor/manifest.js';
import conduction from './circuits/conduction/manifest.js';
import diode from './circuits/diode/manifest.js';
import hallEffect from './circuits/hall-effect/manifest.js';
import mosfetInside from './circuits/mosfet-inside/manifest.js';
import pnJunction from './circuits/pn-junction/manifest.js';
import rcCharging from './circuits/rc-charging/manifest.js';
import rnmosNot from './circuits/rnmos-not/manifest.js';
import siliconLattice from './circuits/silicon-lattice/manifest.js';
import transistor from './circuits/transistor/manifest.js';

// discrete
import arrangements from './discrete/arrangements/manifest.js';
import bayes from './discrete/bayes/manifest.js';
import binomial from './discrete/binomial/manifest.js';
import combinationStudio from './discrete/combination-studio/manifest.js';
import countingSlots from './discrete/counting-slots/manifest.js';
import countingTree from './discrete/counting-tree/manifest.js';
import expectedValue from './discrete/expected-value/manifest.js';
import hypergeometric from './discrete/hypergeometric/manifest.js';
import inductionLadder from './discrete/induction-ladder/manifest.js';
import invariantDetective from './discrete/invariant-detective/manifest.js';
import karnaugh from './discrete/karnaugh/manifest.js';
import lln from './discrete/lln/manifest.js';
import modularClock from './discrete/modular-clock/manifest.js';
import monteCarlo from './discrete/monte-carlo/manifest.js';
import montyHall from './discrete/monty-hall/manifest.js';
import outcomeBuilder from './discrete/outcome-builder/manifest.js';
import pascal from './discrete/pascal/manifest.js';
import pigeonholeAdversary from './discrete/pigeonhole-adversary/manifest.js';
import proofBuilder from './discrete/proof-builder/manifest.js';
import recurrenceBuilder from './discrete/recurrence-builder/manifest.js';
import ruleCard from './discrete/rule-card/manifest.js';
import sampleSpace from './discrete/sample-space/manifest.js';
import selection from './discrete/selection/manifest.js';
import statementLogic from './discrete/statement-logic/manifest.js';
import truthTable from './discrete/truth-table/manifest.js';
import venn from './discrete/venn/manifest.js';

// economics
import demandShiftVsMove from './economics/demand-shift-vs-move/manifest.js';
import elasticityRevenue from './economics/elasticity-revenue/manifest.js';
import marketEquilibrium from './economics/market-equilibrium/manifest.js';

// exam
import examQuestion from './exam/exam-question/manifest.js';

// geography
import cycle from './geography/cycle/manifest.js';

// geometry
import geometryBoard from './geometry/geometry-board/manifest.js';
import intersectingCircles from './geometry/intersecting-circles/manifest.js';

// ict
import arrayVsList from './ict/array-vs-list/manifest.js';
import baseOdometer from './ict/base-odometer/manifest.js';
import binaryCounter from './ict/binary-counter/manifest.js';
import binaryDisplay from './ict/binary-display/manifest.js';
import binarySearch from './ict/binary-search/manifest.js';
import bitGrouper from './ict/bit-grouper/manifest.js';
import complexityGrowth from './ict/complexity-growth/manifest.js';
import costDerivation from './ict/cost-derivation/manifest.js';
import graphAlgorithm from './ict/graph-algorithm/manifest.js';
import gridPathDp from './ict/grid-path-dp/manifest.js';
import hashTable from './ict/hash-table/manifest.js';
import heapQuest from './ict/heap-quest/manifest.js';
import jkFlipFlop from './ict/jk-flip-flop/manifest.js';
import latchVsFlipFlop from './ict/latch-vs-flip-flop/manifest.js';
import logicBuilder from './ict/logic-builder/manifest.js';
import logicCircuit from './ict/logic-circuit/manifest.js';
import logicGate from './ict/logic-gate/manifest.js';
import placeValueDial from './ict/place-value-dial/manifest.js';
import sequenceDetector from './ict/sequence-detector/manifest.js';
import shiftRegister from './ict/shift-register/manifest.js';
import sortingQuest from './ict/sorting-quest/manifest.js';
import srLatch from './ict/sr-latch/manifest.js';
import treeQuest from './ict/tree-quest/manifest.js';
import twosComplement from './ict/twos-complement/manifest.js';
import wireAChip from './ict/wire-a-chip/manifest.js';

// language
import agreement from './language/agreement/manifest.js';
import articleLens from './language/article-lens/manifest.js';
import cloze from './language/cloze/manifest.js';
import dictation from './language/dictation/manifest.js';
import errorCorrect from './language/error-correct/manifest.js';
import listening from './language/listening/manifest.js';
import preposition from './language/preposition/manifest.js';
import reading from './language/reading/manifest.js';
import sentenceBuilder from './language/sentence-builder/manifest.js';
import transform from './language/transform/manifest.js';
import wordMatch from './language/word-match/manifest.js';

// math
import areaModel from './math/area-model/manifest.js';
import areaRearrange from './math/area-rearrange/manifest.js';
import balanceAlgebra from './math/balance-algebra/manifest.js';
import bearings from './math/bearings/manifest.js';
import boundsWindow from './math/bounds-window/manifest.js';
import brokenTree from './math/broken-tree/manifest.js';
import circleGeometry from './math/circle-geometry/manifest.js';
import complexPlane from './math/complex-plane/manifest.js';
import conic from './math/conic/manifest.js';
import customScene from './math/custom-scene/manifest.js';
import derivation from './math/derivation/manifest.js';
import derivativeExplorer from './math/derivative-explorer/manifest.js';
import differentialEquation from './math/differential-equation/manifest.js';
import divisionWorkbench from './math/division-workbench/manifest.js';
import domainRange from './math/domain-range/manifest.js';
import exactTriangle from './math/exact-triangle/manifest.js';
import expressionOrder from './math/expression-order/manifest.js';
import fractionBar from './math/fraction-bar/manifest.js';
import functionMachine from './math/function-machine/manifest.js';
import fundamentalTheorem from './math/fundamental-theorem/manifest.js';
import geometryFoundations from './math/geometry-foundations/manifest.js';
import geometryTransform from './math/geometry-transform/manifest.js';
import gradientDescent from './math/gradient-descent/manifest.js';
import graph from './math/graph/manifest.js';
import growingPattern from './math/growing-pattern/manifest.js';
import harmonicForm from './math/harmonic-form/manifest.js';
import identityProof from './math/identity-proof/manifest.js';
import integralExplorer from './math/integral-explorer/manifest.js';
import interactiveProblem from './math/interactive-problem/manifest.js';
import iteration from './math/iteration/manifest.js';
import limitExplorer from './math/limit-explorer/manifest.js';
import linearModel from './math/linear-model/manifest.js';
import linearSystem from './math/linear-system/manifest.js';
import linesInSpace from './math/lines-in-space/manifest.js';
import measurement from './math/measurement/manifest.js';
import mysteryBucket from './math/mystery-bucket/manifest.js';
import newtonMethod from './math/newton-method/manifest.js';
import numberLine from './math/number-line/manifest.js';
import numberStructure from './math/number-structure/manifest.js';
import obliqueTriangle from './math/oblique-triangle/manifest.js';
import partialFractions from './math/partial-fractions/manifest.js';
import percentBar from './math/percent-bar/manifest.js';
import phasePortrait from './math/phase-portrait/manifest.js';
import polynomialSolver from './math/polynomial-solver/manifest.js';
import radianWrap from './math/radian-wrap/manifest.js';
import rateMachine from './math/rate-machine/manifest.js';
import ratioShare from './math/ratio-share/manifest.js';
import receiptTotals from './math/receipt-totals/manifest.js';
import sequencePredict from './math/sequence-predict/manifest.js';
import slideRule from './math/slide-rule/manifest.js';
import solidNet from './math/solid-net/manifest.js';
import solidSlice from './math/solid-slice/manifest.js';
import straightLine from './math/straight-line/manifest.js';
import systemSolve from './math/system-solve/manifest.js';
import taylorSeries from './math/taylor-series/manifest.js';
import triangleTrig from './math/triangle-trig/manifest.js';
import trigExplorer from './math/trig-explorer/manifest.js';
import trigSigns from './math/trig-signs/manifest.js';
import vertexParabola from './math/vertex-parabola/manifest.js';

// ml
import classifierThreshold from './ml/classifier-threshold/manifest.js';
import decisionBoundary from './ml/decision-boundary/manifest.js';
import embeddingSpace from './ml/embedding-space/manifest.js';
import kmeans from './ml/kmeans/manifest.js';
import knn from './ml/knn/manifest.js';
import nextToken from './ml/next-token/manifest.js';
import regression from './ml/regression/manifest.js';

// networking
import ethernetPinout from './networking/ethernet-pinout/manifest.js';
import layerEncapsulation from './networking/layer-encapsulation/manifest.js';
import networkMedia from './networking/network-media/manifest.js';
import packetJourney from './networking/packet-journey/manifest.js';
import subnetBuilder from './networking/subnet-builder/manifest.js';
import switchLearning from './networking/switch-learning/manifest.js';
import vlanDesigner from './networking/vlan-designer/manifest.js';
import vpnTunnel from './networking/vpn-tunnel/manifest.js';

// physics
import alternatingCurrent from './physics/alternating-current/manifest.js';
import atwood from './physics/atwood/manifest.js';
import blochSphere from './physics/bloch-sphere/manifest.js';
import bulletWalls from './physics/bullet-walls/manifest.js';
import carnot from './physics/carnot/manifest.js';
import circularMotion from './physics/circular-motion/manifest.js';
import collisionTrack from './physics/collision-track/manifest.js';
import coupleTorque from './physics/couple-torque/manifest.js';
import doppler from './physics/doppler/manifest.js';
import doubleSlit from './physics/double-slit/manifest.js';
import efficiency from './physics/efficiency/manifest.js';
import electricField from './physics/electric-field/manifest.js';
import electricFlux from './physics/electric-flux/manifest.js';
import energySkate from './physics/energy-skate/manifest.js';
import entropy from './physics/entropy/manifest.js';
import fallingTarget from './physics/falling-target/manifest.js';
import fissionChain from './physics/fission-chain/manifest.js';
import fluidPressure from './physics/fluid-pressure/manifest.js';
import forcePairs from './physics/force-pairs/manifest.js';
import gasProcess from './physics/gas-process/manifest.js';
import gaussLaw from './physics/gauss-law/manifest.js';
import gravitation from './physics/gravitation/manifest.js';
import gravityDrop from './physics/gravity-drop/manifest.js';
import heatTransfer from './physics/heat-transfer/manifest.js';
import heatingCurve from './physics/heating-curve/manifest.js';
import impulse from './physics/impulse/manifest.js';
import intercept from './physics/intercept/manifest.js';
import kepler from './physics/kepler/manifest.js';
import lengthContraction from './physics/length-contraction/manifest.js';
import lensImaging from './physics/lens-imaging/manifest.js';
import lever from './physics/lever/manifest.js';
import linearPursuit from './physics/linear-pursuit/manifest.js';
import lorentz from './physics/lorentz/manifest.js';
import lorentzTransformation from './physics/lorentz-transformation/manifest.js';
import magnetism from './physics/magnetism/manifest.js';
import mirrorImaging from './physics/mirror-imaging/manifest.js';
import movingLauncher from './physics/moving-launcher/manifest.js';
import muonSurvival from './physics/muon-survival/manifest.js';
import nuclearBindingEnergy from './physics/nuclear-binding-energy/manifest.js';
import optics from './physics/optics/manifest.js';
import orbitLab from './physics/orbit-lab/manifest.js';
import photoelectricEffect from './physics/photoelectric-effect/manifest.js';
import power from './physics/power/manifest.js';
import projectileLab from './physics/projectile-lab/manifest.js';
import quantumGates from './physics/quantum-gates/manifest.js';
import rainRelative from './physics/rain-relative/manifest.js';
import rampForces from './physics/ramp-forces/manifest.js';
import refraction from './physics/refraction/manifest.js';
import relativityLightClock from './physics/relativity-light-clock/manifest.js';
import relativitySimultaneity from './physics/relativity-simultaneity/manifest.js';
import rippleTank from './physics/ripple-tank/manifest.js';
import riverBoat from './physics/river-boat/manifest.js';
import shm from './physics/shm/manifest.js';
import spatialLorentz from './physics/spatial-lorentz/manifest.js';
import stoppingDistance from './physics/stopping-distance/manifest.js';
import stressStrain from './physics/stress-strain/manifest.js';
import stringReflection from './physics/string-reflection/manifest.js';
import temperatureScales from './physics/temperature-scales/manifest.js';
import terminalVelocity from './physics/terminal-velocity/manifest.js';
import thermalExpansion from './physics/thermal-expansion/manifest.js';
import uncertaintyWavePacket from './physics/uncertainty-wave-packet/manifest.js';
import vectorBoard from './physics/vector-board/manifest.js';
import vectorTypes from './physics/vector-types/manifest.js';
import venturi from './physics/venturi/manifest.js';
import waterDensity from './physics/water-density/manifest.js';
import waveLab from './physics/wave-lab/manifest.js';
import workEnergy from './physics/work-energy/manifest.js';
import workPotential from './physics/work-potential/manifest.js';
import xrayAttenuation from './physics/xray-attenuation/manifest.js';
import xrayTubeSpectrum from './physics/xray-tube-spectrum/manifest.js';

// statistics
import centerSpread from './statistics/center-spread/manifest.js';
import frequencyDensity from './statistics/frequency-density/manifest.js';
import galton from './statistics/galton/manifest.js';
import histogram from './statistics/histogram/manifest.js';
import normal from './statistics/normal/manifest.js';
import ogive from './statistics/ogive/manifest.js';
import sampling from './statistics/sampling/manifest.js';
import series from './statistics/series/manifest.js';
import zTable from './statistics/z-table/manifest.js';

export const labManifests: readonly LabManifest[] = [
  // accounting
  apportion, breakEven, businessLesson, compoundInterest, depreciation, eoq, equationBalance, journalPoster,
  limitedCompany, ratioLab, reorderPoint, statementBuilder, statementSorter, warehouseAllocation,
  // biology
  cellEnergy, cellSystem, centralDogma, enzymeRate, geneticCross, meiosisExplorer, membraneTransport, mitosisExplorer,
  photosynthesisFactors, punnettCross, respiration, sequence, sexLinkedCross,
  // chem
  atomicOrbital, battery, bohrAtom, crystalLattice, dilution, electrochem, gasBox, kinetics,
  leChatelier, molecularGeometry, orbitalOverlap, periodicTrends, reactionLab, reactionProfile, solutionBox, stereochemistry,
  stoichiometry, titration,
  // circuits
  bjtInside, brownout, capacitorLeak, circuit, circuitBuilder, circuitLab, circuitScene, cmosInverter,
  cmosNand, cmosNor, conduction, diode, hallEffect, mosfetInside, pnJunction, rcCharging,
  rnmosNot, siliconLattice, transistor,
  // discrete
  arrangements, bayes, binomial, combinationStudio, countingSlots, countingTree, expectedValue, hypergeometric,
  inductionLadder, invariantDetective, karnaugh, lln, modularClock, monteCarlo, montyHall, outcomeBuilder,
  pascal, pigeonholeAdversary, proofBuilder, recurrenceBuilder, ruleCard, sampleSpace, selection, statementLogic,
  truthTable, venn,
  // economics
  demandShiftVsMove, elasticityRevenue, marketEquilibrium,
  // exam
  examQuestion,
  // geography
  cycle,
  // geometry
  geometryBoard, intersectingCircles,
  // ict
  arrayVsList, baseOdometer, binaryCounter, binaryDisplay, binarySearch, bitGrouper, complexityGrowth, costDerivation,
  graphAlgorithm, gridPathDp, hashTable, heapQuest, jkFlipFlop, latchVsFlipFlop, logicBuilder, logicCircuit,
  logicGate, placeValueDial, sequenceDetector, shiftRegister, sortingQuest, srLatch, treeQuest, twosComplement,
  wireAChip,
  // language
  agreement, articleLens, cloze, dictation, errorCorrect, listening, preposition, reading,
  sentenceBuilder, transform, wordMatch,
  // math
  areaModel, areaRearrange, balanceAlgebra, bearings, boundsWindow, brokenTree, circleGeometry, complexPlane,
  conic, customScene, derivation, derivativeExplorer, differentialEquation, divisionWorkbench, domainRange, exactTriangle,
  expressionOrder, fractionBar, functionMachine, fundamentalTheorem, geometryFoundations, geometryTransform, gradientDescent, graph,
  growingPattern, harmonicForm, identityProof, integralExplorer, interactiveProblem, iteration, limitExplorer, linearModel,
  linearSystem, linesInSpace, measurement, mysteryBucket, newtonMethod, numberLine, numberStructure, obliqueTriangle,
  partialFractions, percentBar, phasePortrait, polynomialSolver, radianWrap, rateMachine, ratioShare, receiptTotals,
  sequencePredict, slideRule, solidNet, solidSlice, straightLine, systemSolve, taylorSeries, triangleTrig,
  trigExplorer, trigSigns, vertexParabola,
  // ml
  classifierThreshold, decisionBoundary, embeddingSpace, kmeans, knn, nextToken, regression,
  // networking
  ethernetPinout, layerEncapsulation, networkMedia, packetJourney, subnetBuilder, switchLearning, vlanDesigner, vpnTunnel,
  // physics
  alternatingCurrent, atwood, blochSphere, bulletWalls, carnot, circularMotion, collisionTrack, coupleTorque,
  doppler, doubleSlit, efficiency, electricField, electricFlux, energySkate, entropy, fallingTarget,
  fissionChain, fluidPressure, forcePairs, gasProcess, gaussLaw, gravitation, gravityDrop, heatTransfer,
  heatingCurve, impulse, intercept, kepler, lengthContraction, lensImaging, lever, linearPursuit,
  lorentz, lorentzTransformation, magnetism, mirrorImaging, movingLauncher, muonSurvival, nuclearBindingEnergy, optics,
  orbitLab, photoelectricEffect, power, projectileLab, quantumGates, rainRelative, rampForces, refraction,
  relativityLightClock, relativitySimultaneity, rippleTank, riverBoat, shm, spatialLorentz, stoppingDistance, stressStrain,
  stringReflection, temperatureScales, terminalVelocity, thermalExpansion, uncertaintyWavePacket, vectorBoard, vectorTypes, venturi,
  waterDensity, waveLab, workEnergy, workPotential, xrayAttenuation, xrayTubeSpectrum,
  // statistics
  centerSpread, frequencyDensity, galton, histogram, normal, ogive, sampling, series,
  zTable,
];
